services:
  app:                    # The name of the service, can be anything
    image: express-server # Declares which image to use
    build:
      context: .          # Path to the Dockerfile
      dockerfile: Dockerfile
    ports:                # Declares the ports to publish
      - 3003:3000
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/tododb?authSource=admin
      - REDIS_URL=redis://redis:6379